#!/bin/bash
start_time=`(date +%s)`
file_name=$(git diff --cached --name-only --diff-filter=ACM)
python3 .git/hooks/heimdall.py $PWD $file_name
output=$?
end_time=`(date +%s)`
duration=$((end_time-start_time))
echo 'It took '$duration 'secs to scan'
exit $output
